### ISSUE TITLE
One Elm plugin

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [rojepp/vscode-elm#2]
OK, so we already have [Elm plugin in VSCode gallery] (https://marketplace.visualstudio.com/items/sbrink.elm) created by @sbrink. I guess we should discuss creating just one Elm plugin.

**Comment by rojepp** [comment]
Cool! Is there anything in this repo that doesn't exist in the other one?

**Comment by sbrink** [comment]
I'm in favor of joining forces. I'm sure we can create the best developing experience for elm in VS Code.

@rojepp Only some snippets in my repository.

**Comment by sbrink** [comment]
What's the best way to continue? I was working on integrating https://github.com/ElmCast/elm-oracle

**Comment by sbrink** [comment]
Just an idea: We could ask Evan Czaplicki if we can move one repository to the elm-lang organization

**Comment by rojepp** [comment]
Integrating elm-oracle does seem to be the next step, and then improving it. :) 
For now, seeing as theres more functionality in your repo, I drop this one and efforts continue in your repo? Everyone agree?

**Comment by rojepp** [comment]
Probably, as the project becomes more mature, it can be moved to elm-lang?

**Comment by sbrink** [comment]
Moving it to elm-lang would be the best solution. Repos within organzation usually get more contributions.

@rojepp: We should use your code for error handling. Mine is a bit hacky...

**Comment by Krzysztof-Cieslak** [comment]
Anyway, we can just drop this one and move development to @sbrink one. 

Moving it to elm-lang will take time I guess (Evan needs to agree for it) and really doesn't have any impact on developing new features.

Elm-oracle is definitely way to go, it can give autocomplete which "big" feature and usually brings lot of users.

Also adding REPL (send line to REPL, send selection to REPL) should be easy to add.

Running elm commands from editor is also easy to add.

...

Well it's Code, either something is easy to add or you can't add it at all ;)

**Comment by rojepp** [comment]
Great, consider this repo dropped!
We can discuss individual additions there.
